---
title: "tightness-regressions"
format: html
---

```{r}
library(tidyverse)
library(brms)
library(car)

ds_FA <- read_csv("../../2026-Sharing-Analyses/sharing-dataset-for-analysis.csv")

tl <- read_csv("../../minerva/Tight-Loose/Datasets/DT-TL-FinalData.csv") %>%
  mutate(
    OWC = str_trim(OWC, side = c("both"))
  )

ds <- full_join(ds_FA, tl, by = c("OWC"))

hz_cat <- read_csv("../../minerva/Hazards/Datasets/DT-hzcats-society-level.csv") %>%
  select(ID, allhazards_est_count_30, disaster_est_count_30, disaster_est_count_30_IA)

ds <- full_join(ds, hz_cat, by = c("ID")) %>%
  mutate(
    General_TL5B_pref_final_bin = ordered(General_TL5B_pref_final,
      levels = c(1, 1.5, 1.75, 2, 2.25, 2.5, 2.75, 3, 3.25, 3.5, 3.75, 4))
  ) %>%
  filter(ID != 73 & ID != 218)

```

```{r}
cor.test(
  ds$ea033,
  ds$General_TL5B_pref_final,
  use = "complete.obs",
  method = "spearman"
)

cor.test(
  ds$class_strat,
  ds$General_TL5B_pref_final,
  use = "complete.obs",
  method = "spearman"
)

cor.test(
  ds$intensity_agricult,
  ds$General_TL5B_pref_final,
  use = "complete.obs",
  method = "spearman"
)

# most significant
cor.test(
  ds$community_size,
  ds$General_TL5B_pref_final,
  use = "complete.obs",
  method = "spearman"
)

```

Control on community size

```{r}
ggplot(ds, aes(x = General_TL5B_pref_final, y = allhazards_nonfd_sev_exposure2_30)) +
  geom_jitter(height = 0.05, alpha = 0.6) +
  geom_smooth(method = "loess", se = FALSE, color = "#66c2a4")

ggplot(ds, aes(x = disaster_h9a_sev_exposure_30, y = General_TL5B_pref_final)) +
  geom_jitter(height = 0.05, alpha = 0.6) +
  geom_smooth(method = "loess", se = FALSE, color = "#66c2a4")

```


## Regressions on variables in cluster analysis
  "disaster_est_count_30_IA",
  "normative_est_count_30_IA",
  "allhazards_H9a_sev_exposure_30_IA",
  "allhazards_nonfd_sev_exposure2_30_IA"

```{r}
vars <- c(
  "disaster_est_count_30_IA",
  "normative_est_count_30_IA",
  "allhazards_H9a_sev_exposure_30_IA",
  "allhazards_nonfd_sev_exposure2_30_IA"
)

ds %>%
  select(all_of(vars)) %>%
  cor(use = "pairwise.complete.obs")
```

  
```{r}
model_vars <- c(
  "General_TL5B_pref_final",
  "disaster_est_count_30",
  "normative_est_count_30",
  "allhazards_H9a_sev_exposure_30",
  "allhazards_nonfd_sev_exposure2_30",
  "community_size"
)

ds_step <- ds %>%
  drop_na(all_of(model_vars))

dis <- lm(
  General_TL5B_pref_final ~
    normative_est_count_30 +
    allhazards_H9a_sev_exposure_30 +
    allhazards_nonfd_sev_exposure2_30+
    community_size,
  data = ds_step
)
summary(dis)
step(dis, direction = "both")


vif(dis)
```

